### ISSUE TITLE
Support With PW Server

### ISSUE THREAD

**Issue by bell6one1** [LibardiFelipe/Perfect-Launcher#3]
Does this support Perfect World 1.4.4 and 1.5.5 servers?

**Comment by LibardiFelipe** [comment]
Yes, it should. I updated the app when the version 1.5.5 was realeased, it is working fine (on oficial servers) since then. The problem is that depending on the server that you play, they might change the folder structure and/or the file names, if that happens, great chances that the app will not work.

**Comment by LibardiFelipe** [comment]
> Does this support Perfect World 1.4.4 and 1.5.5 servers?

Yes, it should. I updated the app when the version 1.5.5 was realeased, it is working fine (on oficial servers) since then. The problem is that depending on the server that you play, they might change the folder structure and/or the file names, if that happens, great chances that the app will not work.
